# -*- coding: utf-8 -*-
"""Apple stock.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sNUmZ3QCoQH1aO2uZqoaXskczRv4bjmO
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_excel("/content/AAPL.xlsx")

df.head()

df.tail()

df.info()

print(df.isnull().sum())

df = df.drop_duplicates()

df["Date"] = pd.to_datetime(df["Date"])

df = df.sort_values("Date")

print(df[["Date"]].head(10))

df["Daily Price Change"] = df["Close"].diff()

print(df[["Daily Price Change"]].head(10))

df["Daily Return"] = ((df["Close"] - df["Open"]) / df["Open"]) * 100
print(df[["Daily Return"]].head(10))

print("\nStock Price Analysis:")
print("Highest Price:", df["High"].max())
print("Lowest Price:", df["Low"].min())
print("Average Closing Price:", df["Close"].mean())

print("\nDaily Price Change:")
df["Daily Percentage Change"] = df["Close"].pct_change() * 100
print(df[["Date", "Close", "Daily Price Change", "Daily Percentage Change"]])

plt.figure(figsize=(10, 5))
plt.plot(df["Date"], df["Close"])
plt.xlabel("Date")
plt.ylabel("Closing Price")
plt.title("AAPL Stock Price Analysis")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

df["Daily Percentage Change"] = df["Close"].pct_change() * 100
print(df[["Daily Percentage Change"]].head(10))

# Sort by 'Daily Percentage Change' to find the biggest losses
biggest_losses = df.sort_values(by='Daily Percentage Change', ascending=True)

print("\nDays with the Biggest Losses:")
print(biggest_losses[['Date', 'Close', 'Daily Percentage Change']].head())

print("\nTrading Volume Analysis:")
print("Average Trading Volume:", df["Volume"].mean())

# Days with Highest Trading Volume
highest_volume_days = df.sort_values(by='Volume', ascending=False)
print("\nDays with Highest Trading Volume:")
print(highest_volume_days[['Date', 'Volume', 'Close']].head())

# Days with Lowest Trading Volume
lowest_volume_days = df.sort_values(by='Volume', ascending=True)
print("\nDays with Lowest Trading Volume:")
print(lowest_volume_days[['Date', 'Volume', 'Close']].head())

