# -*- coding: utf-8 -*-
"""Untitled64.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G4914O1C5beirKVfl_ec5qOtg5lka9JW
"""

import pandas as pd

df = pd.read_csv("shopify_stock.csv")

df["date"] = pd.to_datetime(df["date"])

print(df.head())

import matplotlib.pyplot as plt

plt.figure(figsize=(12, 5))

plt.plot(df["date"], df["close"])

plt.title("Shopify Closing Price Over Time")
plt.xlabel("Date")
plt.ylabel("Closing Price")
plt.grid(True)

plt.show()

df["MA20"] = df["close"].rolling(window=20).mean()
df["MA50"] = df["close"].rolling(window=50).mean()

plt.figure(figsize=(12, 5))

plt.plot(df["date"], df["close"], label="Closing Price")
plt.plot(df["date"], df["MA20"], label="20-Day Moving Average")
plt.plot(df["date"], df["MA50"], label="50-Day Moving Average")

plt.title("Shopify Stock Price with Moving Averages")
plt.xlabel("Date")
plt.ylabel("Price")

plt.legend()
plt.grid(True)

plt.show()

df["Daily_Return"] = df["close"].pct_change()

print(df[["date", "close", "Daily_Return"]].head(10))

plt.figure(figsize=(10, 5))
plt.hist(df["Daily_Return"].dropna(), bins=50)

plt.title("Histogram of Shopify Daily Returns")
plt.xlabel("Daily Return")
plt.ylabel("Frequency")
plt.grid(True)

plt.show()

import seaborn as sns

plt.figure(figsize=(10, 5))

sns.kdeplot(df["Daily_Return"].dropna(), fill=True)

plt.title("KDE Plot of Shopify Daily Returns")
plt.xlabel("Daily Return")
plt.ylabel("Density")

plt.show()

df["Rolling_Volatility"] = df["Daily_Return"].rolling(window=20).std()

print("FINANCIAL INSIGHTS")
print("------------------")

start_price = df["close"].iloc[0]
end_price = df["close"].iloc[-1]

if end_price > start_price:
    print("1. Stock Price Trend: Overall upward trend.")
else:
    print("1. Stock Price Trend: Overall downward trend.")

volatility = df["Daily_Return"].std()

print("2. Stock Stability/Volatility:", volatility)

if volatility < 0.02:
    print("   The stock is relatively stable.")
else:
    print("   The stock is relatively volatile.")

max_date = df.loc[df["Rolling_Volatility"].idxmax(), "date"]
max_volatility = df["Rolling_Volatility"].max()

print("3. High-Volatility Period:", max_date)
print("   Highest 20-day rolling volatility:", max_volatility)